// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Record = {};

var Table = {};

var Base = {};

exports.Record = Record;
exports.Table = Table;
exports.Base = Base;
/* No side effect */
