// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Express = require("bs-express/src/Express.bs.js");
var DotenvFlow = require("dotenv-flow");

var app = Express.express(undefined);

DotenvFlow.config();

exports.app = app;
/* app Not a pure module */
