// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import Airtable from "airtable";

var base = new Airtable({
        apiKey: ""
      }).base("");

var table = Curry._1(base, "");

function getResults(table) {
  return table.select({
                maxRecords: 5,
                view: "Grid view"
              }).firstPage();
}

getResults(table).then(function (results) {
        console.log(results);
        return Promise.resolve(undefined);
      }).catch(function (error) {
      console.log(error);
      return Promise.resolve(undefined);
    });

export {
  base ,
  table ,
  getResults ,
  
}
/* Not a pure module */
