// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Airtable = require("Airtable").default;

var base = Curry._1(Airtable.Base, "appZQ4hJRTJWsowaO");

var testing = Curry._1(base, "Testing");

var all = Curry._1(testing.select, {
      view: "Grid view"
    });

Curry._1(all.firstPage, (function (_error, records) {
        var names = records.map(function (record) {
              return Curry._1(record.get, "Name");
            });
        console.log(names);
        
      }));

exports.base = base;
exports.testing = testing;
exports.all = all;
/* base Not a pure module */
