// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");

function getNullableExn(s, errMsgOpt) {
  var errMsg = errMsgOpt !== undefined ? errMsgOpt : "Value not found";
  if (s == null) {
    return Js_exn.raiseError(errMsg);
  } else {
    return s;
  }
}

function makeArray(a) {
  if (a !== undefined) {
    return a;
  } else {
    return [];
  }
}

exports.getNullableExn = getNullableExn;
exports.makeArray = makeArray;
/* No side effect */
